title = "TOML Example"

[general]
usecudnn = true
usecudnnbenchmark = true
gpuid = 0
loadpretrainedmodel = false
#pretrainedmodelpath = "/file3/xinshuo/data/models/resnet_LSTM_lipreading/trained_model_20181129_05h51m12s/trained_model_epoch003.pt"
pretrainedmodelpath = "/media/xinshuo/Data/models/resnet_LSTM_lipreading/trained_model_20181129_05h51m24s/trained_model_epoch001.pt"
savemodel = true
modelsavedir = "/media/xinshuo/Data/models/resnet_LSTM_lipreading"
#modelsavedir = "/file3/xinshuo/data/models/resnet_LSTM_lipreading"

#logfile = ""
dataset = "/media/xinshuo/Data/Datasets/LRD/LRW/lipread_mp4"
#dataset = "/file3/xinshuo/data/datasets/LRD/LRW/lipread_mp4"

num_frames = 29

[input]
batchsize = 25
#batchsize = 2
numworkers = 25
#numworkers = 2

[model]
#type = "temp-conv"
type = "LSTM"
inputdim = 256
hiddendim = 256
numclasses = 500
numlstms = 2

[training]
train = true
startepoch = 4
endepoch = 15
statsfrequency = 10
learningrate = 0.003
momentum = 0.9
weightdecay = 0.0003
shuffle = true

[validation]
validate = false
saveaccuracy = true

[testing]
test = true
saveaccuracy = true